backend:
  name: git-gateway
  branch: main  # 你的仓库主分支（保持和GitHub一致）

media_folder: "static/images/uploads"  # 图片存储目录（自动创建）
public_folder: "/images/uploads"       # 图片访问URL前缀

collections:
  - name: "pages"
    label: "页面"
    files:
      - file: "index.html"  # 你的首页文件名（修正拼写！原错误：index.ntal）
        name: "home"
        label: "首页"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "内容", name: "content", widget: "markdown"}
