backend:  
  name: git-gateway  
  branch: main  

media_folder: "coinmint_clone/static/images/uploads"  
public_folder: "/static/images/uploads"  

collections:  
  - name: "pages"  
    label: "页面"  
    files:  
      - file: "coinmint_clone/index.html"  # 首页路径（在coinmint_clone下）  
        name: "home"  
        label: "首页"  
        fields:  
          - {label: "标题", name: "title", widget: "string"}  
          - {label: "内容", name: "content", widget: "markdown"}  
